import React from 'react';
import {
  Search,
  ShoppingBag,
  ShoppingCart,
  Heart,
  User,
  Menu,
  X,
  Star,
  ArrowLeft,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Check,
  CheckCircle2,
  BadgeCheck,
  ShieldCheck,
  Truck,
  Headphones,
  Phone,
  Mail,
  ThumbsUp,
  Droplet,
  Sparkles,
  Flower2,
  Leaf,
  FlaskConical,
  Paintbrush,
  Clock,
  Package,
  Receipt,
  RotateCcw,
  Trash2,
  Plus,
  Minus,
  MapPin,
  Home,
  LayoutGrid,
  BookOpen,
  MessageSquare,
  PhoneCall,
  CreditCard,
  LayoutDashboard,
  Download,
  Grid,
  List,
  Lock,
  LogOut,
  Bell,
  Percent,
  QrCode,
  Gift,
  Rocket,
  Tag,
  Settings,
  ArrowUpDown,
  SlidersHorizontal,
  ZoomIn,
  Award,
  Wallet,
  Navigation,
  Snowflake,
  Flame,
  HeartPulse,
  Brain,
  LucideProps,
} from 'lucide-react';

export interface IconProps extends Omit<LucideProps, 'ref'> {
  name: string;
  size?: number | string;
  filled?: boolean;
  title?: string;
}

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  search: Search,
  search_off: Search,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  add_shopping_cart: ShoppingCart,
  favorite: Heart,
  favorite_border: Heart,
  person: User,
  menu: Menu,
  close: X,
  star: Star,
  arrow_back: ArrowLeft,
  arrow_back_ios: ChevronLeft,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  keyboard_arrow_down: ChevronDown,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  check: Check,
  check_circle: CheckCircle2,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  security: ShieldCheck,
  local_shipping: Truck,
  support_agent: Headphones,
  call: Phone,
  mail: Mail,
  thumb_up: ThumbsUp,
  water_drop: Droplet,
  flare: Sparkles,
  auto_awesome: Sparkles,
  spa: Flower2,
  forest: Leaf,
  eco: Leaf,
  science: FlaskConical,
  brush: Paintbrush,
  format_paint: Paintbrush,
  clean_hands: Sparkles,
  sanitizer: Droplet,
  timeline: Clock,
  schedule: Clock,
  inventory_2: Package,
  package_2: Package,
  receipt: Receipt,
  receipt_long: Receipt,
  replay: RotateCcw,
  cached: RotateCcw,
  refresh: RotateCcw,
  sync: RotateCcw,
  delete: Trash2,
  delete_sweep: Trash2,
  add: Plus,
  remove: Minus,
  location_on: MapPin,
  home_pin: MapPin,
  place: MapPin,
  home: Home,
  category: LayoutGrid,
  auto_stories: BookOpen,
  chat: MessageSquare,
  contact_phone: PhoneCall,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  download: Download,
  grid_view: Grid,
  view_agenda: List,
  lock: Lock,
  logout: LogOut,
  notifications: Bell,
  percent: Percent,
  qr_code_scanner: QrCode,
  rate_review: MessageSquare,
  redeem: Gift,
  rocket_launch: Rocket,
  sell: Tag,
  local_offer: Tag,
  settings: Settings,
  sort: ArrowUpDown,
  tune: SlidersHorizontal,
  zoom_in: ZoomIn,
  award_star: Award,
  loyalty: Award,
  account_balance_wallet: Wallet,
  near_me: Navigation,
  ac_unit: Snowflake,
  local_fire_department: Flame,
  medication: HeartPulse,
  health_and_safety: HeartPulse,
  psychology: Brain,
  psychology_alt: Brain,
  face: Sparkles,
  visibility: Sparkles,
  haircare: Sparkles,
  fragrance: FlaskConical,
  tools: Paintbrush,
};

export const Icon: React.FC<IconProps> = ({
  name,
  size = 18,
  className = '',
  filled = false,
  ...props
}) => {
  const normalizedName = (name || '').trim().toLowerCase();
  const IconComponent = iconMap[normalizedName] || Sparkles;

  const fillClasses = filled
    ? normalizedName === 'star'
      ? 'fill-amber-400 stroke-amber-400'
      : normalizedName === 'favorite' || normalizedName === 'heart'
      ? 'fill-rose-500 stroke-rose-500'
      : 'fill-current'
    : '';

  return (
    <IconComponent
      size={size}
      className={`inline-block shrink-0 ${fillClasses} ${className}`}
      {...props}
    />
  );
};

export default Icon;
